services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    # networks:
    #   - abb-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    # depends_on:
    #   - ml_service
    # networks:
    #   - abb-network
    # volumes:
    #   - ./data:/app/data

  # ml_service:
  #   build: ./ml_service
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - abb-network
  #   volumes:
  #     - ./data:/app/data

networks:
  abb-network:
